version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    environment:
      - PYTHONUNBUFFERED=1
      - PNPM_HOME=/pnpm
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh run.sh

volumes:
  app-data:
